name: vendor_fixed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  flutter_riverpod: ^2.6.1
  get: ^4.7.2
  google_fonts: ^6.1.0
  flutter_feather_icons: ^2.0.0+1
  firebase_core: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
